changelog:
  exclude:
    authors:
      - dependabot
  categories:
    - title: 🎉 Features
      labels:
        - "Type: Enhancement"
    - title: 🐞 Bugs
      labels:
        - "Type: Bug"
    - title: 🔨 Maintenance
      labels:
        - "Type: Maintenance"
    - title: Other Changes
      labels:
        - "*"